M48
; DRILL file {KiCad 7.0.5} date Mon Nov 27 09:45:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-27T09:45:21+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X1.281Y-1.354
X1.29Y-3.603
X5.849Y-3.607
X5.85Y-1.348
T0
M30
